service: wikimedia-bot

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: ["dynamodb:GetItem", "dynamodb:PutItem"]
          Resource:
            {
              "Fn::Sub": "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/wikimedia_bot",
            }
        - Effect: "Allow"
          Action: ["ssm:GetParameter"]
          Resource:
            {
              "Fn::Sub": "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/wikimedia_bot/*",
            }

package:
  patterns:
    - "!node_modules/**"

functions:
  makePost:
    timeout: 60
    handler: handler.handler
    events:
      # Invoke Lambda function once every 8 hours
      - schedule: rate(8 hours)

plugins:
  - serverless-python-requirements
